// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Asa5XiuWrhTB6CPT2lxp5eqVz5CDoQY',
    appId: '1:986982421255:web:9415fa339f5f3e60746ba2',
    messagingSenderId: '986982421255',
    projectId: 'realtimedatabase-787a3',
    authDomain: 'realtimedatabase-787a3.firebaseapp.com',
    databaseURL: 'https://realtimedatabase-787a3-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-787a3.firebasestorage.app',
    measurementId: 'G-TH0ZLD7BK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0rtq6fBfi6DCtIPDeGwJaLUuzWrnw80',
    appId: '1:986982421255:android:4ef2ff9eebb559ac746ba2',
    messagingSenderId: '986982421255',
    projectId: 'realtimedatabase-787a3',
    databaseURL: 'https://realtimedatabase-787a3-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-787a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaqSypGPvbytTWcFMIpGH7BYd1BBlhqmE',
    appId: '1:986982421255:ios:a957afe972f140dd746ba2',
    messagingSenderId: '986982421255',
    projectId: 'realtimedatabase-787a3',
    databaseURL: 'https://realtimedatabase-787a3-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-787a3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaqSypGPvbytTWcFMIpGH7BYd1BBlhqmE',
    appId: '1:986982421255:ios:a957afe972f140dd746ba2',
    messagingSenderId: '986982421255',
    projectId: 'realtimedatabase-787a3',
    databaseURL: 'https://realtimedatabase-787a3-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-787a3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Asa5XiuWrhTB6CPT2lxp5eqVz5CDoQY',
    appId: '1:986982421255:web:5e1420628b2e20c6746ba2',
    messagingSenderId: '986982421255',
    projectId: 'realtimedatabase-787a3',
    authDomain: 'realtimedatabase-787a3.firebaseapp.com',
    databaseURL: 'https://realtimedatabase-787a3-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-787a3.firebasestorage.app',
    measurementId: 'G-EMVEMZG0ZS',
  );
}
